init_functor_null< miller::index<> > results in a build error on my 32bit test machine. Changing to just initialise for the moment.
g++ -o dials/array_family/boost_python/flex_prediction.o -c -DBOOST_PYTHON_MAX_BASES=2 -I/dls/mx-scratch/upc86896/cctbx/sources/boost -fPIC -fno-strict-aliasing -Wall -Wno-sign-compare -Wno-unknown-pragmas -Wno-parentheses -Winit-self -DNDEBUG -O3 -ffast-math -DBOOST_ALL_NO_LIB -I/dls/mx-scratch/upc86896/cctbx/build_32bit/include -I/dls/mx-scratch/upc86896/cctbx/sources/cctbx_project -I/dls/mx-scratch/upc86896/cctbx/build_32bit/base/include/python2.7 -I/dls/mx-scratch/upc86896/cctbx/sources /dls/mx-scratch/upc86896/cctbx/sources/dials/array_family/boost_python/flex_prediction.cc
/dls/mx-scratch/upc86896/cctbx/sources/cctbx_project/scitbx/array_family/detail/misc.h: In member function 'void scitbx::af::init_functor_null<ElementType>::operator()(ElementType*, const size_t&) const [with ElementType = cctbx::miller::index<int>]':
/dls/mx-scratch/upc86896/cctbx/sources/cctbx_project/scitbx/array_family/shared_plain.h:152:   instantiated from 'scitbx::af::shared_plain<ElementType>::shared_plain(const size_t&, const scitbx::af::init_functor<FunctorType>&) [with FunctorType = scitbx::af::init_functor_null<cctbx::miller::index<int> >, ElementType = cctbx::miller::index<int>]'
/dls/mx-scratch/upc86896/cctbx/sources/cctbx_project/scitbx/array_family/shared.h:39:   instantiated from 'scitbx::af::shared<ElementType>::shared(const size_t&, const scitbx::af::init_functor<FunctorType>&) [with FunctorType = scitbx::af::init_functor_null<cctbx::miller::index<int> >, ElementType = cctbx::miller::index<int>]'
/dls/mx-scratch/upc86896/cctbx/sources/dials/array_family/boost_python/flex_prediction.cc:37:   instantiated from here
/dls/mx-scratch/upc86896/cctbx/sources/cctbx_project/scitbx/array_family/detail/misc.h:44: error: invalid application of 'sizeof' to incomplete type 'boost::STATIC_ASSERTION_FAILURE<false>'