Fix for image viewer mask tool broken by 86f27a4f36843e566d326f4fa9e5f8708761d7f3
Change to importing range from six.moves meant that range now returns an xrange
instance, which is not sliceable:

>>> range(10)
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
>>> range(10)[:]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
>>> from six.moves import range
>>> range(10)
xrange(10)
>>> range(10)[:]
Traceback (most recent call last):
  Python Shell, prompt 19, line 1
TypeError: sequence index must be integer, not 'slice'